# Generated by Django 2.1.5 on 2019-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190131_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_hours',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
